#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use app\console\User;

$application = new Application();
$commands = (require __DIR__ . '/config/command.php');

foreach ($commands as $command) {
    $application->add(new $command);
}

$application->run();