#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use app\console\User;

$application = new Application();

$application->add(new User());

$application->run();